# Generated by Django 4.1.7 on 2023-05-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('describe', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='@', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.articles')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.category'),
        ),
    ]
