# Generated by Django 4.1.7 on 2023-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articles_category_user_age_user_email_user_is_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
