# Generated by Django 4.1.7 on 2023-05-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reviews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='@', max_length=50, unique=True),
        ),
    ]
