# Generated by Django 4.1.7 on 2023-05-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.articles')),
            ],
        ),
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='sn', max_length=50),
        ),
        migrations.DeleteModel(
            name='favourites',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
        migrations.AddField(
            model_name='article_status',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.statuses'),
        ),
        migrations.AddField(
            model_name='article_status',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.user'),
        ),
    ]
