# Generated by Django 4.1.7 on 2023-05-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_articles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_id',
            field=models.IntegerField(),
        ),
    ]
